# Generated by Django 4.1.9 on 2023-06-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='message',
            new_name='message_content',
        ),
    ]
